version: '3.8'

services:
  frontend:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile if it's named differently
    ports:
      - "5173:5173"  # Map the container port to host port 5173
    environment:
      - NODE_ENV=production  # Set environment variables for production
    volumes:
      - .:/usr/src/app  # Mount the current directory to the container